// Razorpay Plan IDs (तुम्हारे account से)
export const subscriptionPlans = [
  {
    id: "plan_TiYGJNIjRKRUnU",
    name: "Basic",
    price: 999,
    period: "/month",
    description: "Small businesses ke liye perfect",
    features: [
      "Website hosting",
      "Monthly maintenance",
      "1 content update/month",
      "SSL certificate",
      "Email support",
      "99.9% uptime",
    ],
    popular: false,
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "plan_TiYIo59SNnPNzy",
    name: "Pro",
    price: 1499,
    period: "/month",
    description: "Growing businesses ke liye best",
    features: [
      "Everything in Basic",
      "SEO optimization",
      "Google Analytics setup",
      "Monthly reports",
      "Priority support",
      "Speed optimization",
      "2 content updates/month",
    ],
    popular: true,
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "plan_TiYJv0qJFaLrdj",
    name: "Business",
    price: 1999,
    period: "/month",
    description: "Complete solution for enterprises",
    features: [
      "Everything in Pro",
      "E-commerce integration",
      "Payment gateway setup",
      "Social media marketing",
      "Custom features",
      "Dedicated account manager",
      "Unlimited updates",
      "24/7 support",
    ],
    popular: false,
    color: "from-orange-500 to-red-500",
  },
];
